[[constraint]]
  branch = "master"
  name = "github.com/araddon/dateparse"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = ">=1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/jasonlvhit/gocron"

[[constraint]]
  name = "github.com/lib/pq"
  version = ">=1.0.0"

[prune]
  go-tests = true
  unused-packages = true
